// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Service.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace TradingSystem.Core {
  public static partial class Service
  {
    static readonly string __ServiceName = "TradingSystem.Core.Service";

    static readonly grpc::Marshaller<global::TradingSystem.Core.OrderMsg> __Marshaller_OrderMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TradingSystem.Core.OrderMsg.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TradingSystem.Core.ErrorCodeMsg> __Marshaller_ErrorCodeMsg = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TradingSystem.Core.ErrorCodeMsg.Parser.ParseFrom);

    static readonly grpc::Method<global::TradingSystem.Core.OrderMsg, global::TradingSystem.Core.ErrorCodeMsg> __Method_EnterOrder = new grpc::Method<global::TradingSystem.Core.OrderMsg, global::TradingSystem.Core.ErrorCodeMsg>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EnterOrder",
        __Marshaller_OrderMsg,
        __Marshaller_ErrorCodeMsg);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TradingSystem.Core.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Service</summary>
    public abstract partial class ServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TradingSystem.Core.ErrorCodeMsg> EnterOrder(global::TradingSystem.Core.OrderMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Service</summary>
    public partial class ServiceClient : grpc::ClientBase<ServiceClient>
    {
      /// <summary>Creates a new client for Service</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Service that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TradingSystem.Core.ErrorCodeMsg EnterOrder(global::TradingSystem.Core.OrderMsg request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return EnterOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TradingSystem.Core.ErrorCodeMsg EnterOrder(global::TradingSystem.Core.OrderMsg request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EnterOrder, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TradingSystem.Core.ErrorCodeMsg> EnterOrderAsync(global::TradingSystem.Core.OrderMsg request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return EnterOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TradingSystem.Core.ErrorCodeMsg> EnterOrderAsync(global::TradingSystem.Core.OrderMsg request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EnterOrder, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_EnterOrder, serviceImpl.EnterOrder).Build();
    }

  }
}
#endregion
